spring:
#  flyway:
#    url: "jdbc:mysql://localhost:3306/dbdemo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
#    user: root
#    password: hellodb
#    baseline-on-migrate: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/dbdemo"
    password: root
    username: hellodb
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
#flyway:
#  url: jdbc:mysql://localhost:3306
#  schemas: dbdemo
#  user: root
#  password: hellodb